on:
  push:
    branches:
      - master

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Master
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_SECRET }}
          server-dir: /public_html/
          exclude: |
            **/wp-content/uploads/**
            .htaccess
